module.exports = Object.freeze({
  Action: require('./lib/action'),
  Attribute: require('./lib/attribute'),
  AttributeModifier: require('./lib/attribute-modifier'),
  Condition: require('./lib/condition'),
  Context: require('./lib/context'),
  ContinuousAttribute: require('./lib/continuous-attribute'),
  GameObject: require('./lib/game-object'),
  DiscreteAttribute: require('./lib/discrete-attribute'),
  Effect: require('./lib/effect'),
  Event: require('./lib/event'),
  EventHandler: require('./lib/event-handler'),
  Flag: require('./lib/flag'),
  Instance: require('./lib/instance'),
  Modifier: require('./lib/modifier'),
  OutputGenerator: require('./lib/output-generator'),
  Result: require('./lib/result'),
  Selection: require('./lib/selection'),
  StatusEffect: require('./lib/status-effect'),
  Strategy: require('./lib/strategy'),
  Unit: require('./lib/unit'),
  Utils: require('./lib/utils'),
  Value: require('./lib/value')
})
